apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-dep-deployment
  template:
    metadata:
      labels:
        app: fastapi-dep-deployment
    spec:
      containers:
        - name: fastapi-dep
          image: elghibaomar/fastapi-dep:latest
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 8181


---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-dep-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8181
  selector:
    app: fastapi-dep-deployment